# need to load gtest using new_git_repository instead of a submodule

cc_library(
    name = "representations",
    srcs = ["Representations.cpp"],
    hdrs = ["rep.h"],
    visibility = ["//visibility:public"], # prob. just bin and test
    deps = [
        "//Utilities",
    ],
)
